load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "AEXML",
    module_name = "AEXML",
    srcs = glob(["*.swift"]),
    copts = [
        "-DSWIFT_PACKAGE",
    ],
    visibility = ["//visibility:public"],
 )
