name: Bazel

on:
  push:
    branches: [master, main]
    paths:
      - 'Sources/**/*.swift'
      - 'Tests/**/*.swift'
      - 'Tests/**/*.xml'
      - '**/BUILD'
      - 'WORKSPACE'
  pull_request:
    paths:
      - 'Sources/**/*.swift'
      - 'Tests/**/*.swift'
      - 'Tests/**/*.xml'
      - '**/BUILD'
      - 'WORKSPACE'

jobs:
  MacOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: AEXML tests
        if: always()
        run: bazelisk test //Tests:AEXMLTests --test_env=BUILD_WORKSPACE_DIRECTORY=$(bazelisk info workspace)
        shell: bash
  Linux:
    strategy:
      matrix:
        tag: ['5.1', '5.2', '5.3']
    runs-on: ubuntu-latest
    container:
      image: swift:${{ matrix.tag }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1' # The Go version to download (if necessary) and use.
      - name: Setup Bazel
        if: always()
        run: go get github.com/bazelbuild/bazelisk
        shell: bash
      - name: AEXML tests
        if: always()
        run: |
             CC=clang bazelisk test //Tests:AEXMLTests --action_env=PATH --test_env=BUILD_WORKSPACE_DIRECTORY=$(bazelisk info workspace)
        shell: bash
